#pragma once

#include <map>
#include <cstdint>

enum whisper_diar_tensor {
    WHISPER_DIAR_TENSOR_MEL_FILTERS,
    WHISPER_DIAR_TENSOR_SILENCE_EMBEDDING,
    WHISPER_DIAR_TENSOR_ENC_PRE_ENCODE_WEIGHT,
    WHISPER_DIAR_TENSOR_ENC_EMBED_NORM_WEIGHT,
    WHISPER_DIAR_TENSOR_ENC_EMBED_NORM_BIAS,
    WHISPER_DIAR_TENSOR_ENC_FINAL_NORM_WEIGHT,
    WHISPER_DIAR_TENSOR_ENC_FINAL_NORM_BIAS,
    WHISPER_DIAR_TENSOR_ENC_PROJ_WEIGHT,
    WHISPER_DIAR_TENSOR_ENC_PROJ_BIAS,
    WHISPER_DIAR_TENSOR_UPSAMPLE_WEIGHT,
    WHISPER_DIAR_TENSOR_UPSAMPLE_BIAS,
    WHISPER_DIAR_TENSOR_HEAD_HIDDEN_WEIGHT,
    WHISPER_DIAR_TENSOR_HEAD_HIDDEN_BIAS,
    WHISPER_DIAR_TENSOR_HEAD_SPEAKERS_WEIGHT,
    WHISPER_DIAR_TENSOR_HEAD_SPEAKERS_BIAS,
    WHISPER_DIAR_TENSOR_ENC_NORM1_WEIGHT,
    WHISPER_DIAR_TENSOR_ENC_NORM1_BIAS,
    WHISPER_DIAR_TENSOR_ENC_ATTN_QKV_WEIGHT,
    WHISPER_DIAR_TENSOR_ENC_ATTN_OUT_WEIGHT,
    WHISPER_DIAR_TENSOR_ENC_ATTN_OUT_BIAS,
    WHISPER_DIAR_TENSOR_ENC_NORM2_WEIGHT,
    WHISPER_DIAR_TENSOR_ENC_NORM2_BIAS,
    WHISPER_DIAR_TENSOR_ENC_FFN1_WEIGHT,
    WHISPER_DIAR_TENSOR_ENC_FFN1_BIAS,
    WHISPER_DIAR_TENSOR_ENC_FFN2_WEIGHT,
    WHISPER_DIAR_TENSOR_ENC_FFN2_BIAS,
    WHISPER_DIAR_TENSOR_ACTIVITY_HEAD0_WEIGHT,
    WHISPER_DIAR_TENSOR_ACTIVITY_HEAD0_BIAS,
    WHISPER_DIAR_TENSOR_ACTIVITY_HEAD1_WEIGHT,
    WHISPER_DIAR_TENSOR_ACTIVITY_HEAD1_BIAS,
};

enum whisper_diar_hparam {
    WHISPER_DIAR_HPARAM_ARCHITECTURE,
    WHISPER_DIAR_HPARAM_VERSION,
    WHISPER_DIAR_HPARAM_ENCODER_TYPE,
    WHISPER_DIAR_HPARAM_SUBSAMPLING_TYPE,
    WHISPER_DIAR_HPARAM_ENCODER_D_MODEL,
    WHISPER_DIAR_HPARAM_ENCODER_N_HEADS,
    WHISPER_DIAR_HPARAM_ENCODER_D_FF,
    WHISPER_DIAR_HPARAM_ENCODER_SUBSAMPLING_FACTOR,
    WHISPER_DIAR_HPARAM_TRANSFORMER_HIDDEN_SIZE,
    WHISPER_DIAR_HPARAM_ENCODER_N_LAYERS,
    WHISPER_DIAR_HPARAM_NUM_SPEAKERS,
    WHISPER_DIAR_HPARAM_ENCODER_POS_EMB_MAX_LEN,
    WHISPER_DIAR_HPARAM_PREPROCESSOR_N_FFT,
    WHISPER_DIAR_HPARAM_PREPROCESSOR_FEATURES,
    WHISPER_DIAR_HPARAM_PREPROCESSOR_PREEMPH,
    WHISPER_DIAR_HPARAM_PREPROCESSOR_LOG_ZERO_GUARD,
    WHISPER_DIAR_HPARAM_ENCODER_ROPE_BASE,
    WHISPER_DIAR_HPARAM_SCORING_SPKCACHE_SIL_FRAMES_PER_SPK,
    WHISPER_DIAR_HPARAM_SCORING_PRED_SCORE_THRESHOLD,
    WHISPER_DIAR_HPARAM_SCORING_SCORES_BOOST_LATEST,
    WHISPER_DIAR_HPARAM_SCORING_STRONG_BOOST_RATE,
    WHISPER_DIAR_HPARAM_SCORING_WEAK_BOOST_RATE,
    WHISPER_DIAR_HPARAM_SCORING_MIN_POS_SCORES_RATE,
};

static const std::map<whisper_diar_tensor, const char *> WHISPER_DIAR_TENSOR_NAMES = {
    {WHISPER_DIAR_TENSOR_MEL_FILTERS,           "preprocessor.fb"},
    {WHISPER_DIAR_TENSOR_SILENCE_EMBEDDING,     "learnable_sil_emb"},
    {WHISPER_DIAR_TENSOR_ENC_PRE_ENCODE_WEIGHT, "encoder.pre_encode.proj.weight"},
    {WHISPER_DIAR_TENSOR_ENC_EMBED_NORM_WEIGHT, "encoder.embed_norm.weight"},
    {WHISPER_DIAR_TENSOR_ENC_EMBED_NORM_BIAS,   "encoder.embed_norm.bias"},
    {WHISPER_DIAR_TENSOR_ENC_FINAL_NORM_WEIGHT, "encoder.final_norm.weight"},
    {WHISPER_DIAR_TENSOR_ENC_FINAL_NORM_BIAS,   "encoder.final_norm.bias"},
    {WHISPER_DIAR_TENSOR_ENC_PROJ_WEIGHT,       "encoder_proj.weight"},
    {WHISPER_DIAR_TENSOR_ENC_PROJ_BIAS,         "encoder_proj.bias"},
    {WHISPER_DIAR_TENSOR_UPSAMPLE_WEIGHT,       "subpixel_upsample.weight"},
    {WHISPER_DIAR_TENSOR_UPSAMPLE_BIAS,         "subpixel_upsample.bias"},
    {WHISPER_DIAR_TENSOR_HEAD_HIDDEN_WEIGHT,    "head.first_hidden_to_hidden.weight"},
    {WHISPER_DIAR_TENSOR_HEAD_HIDDEN_BIAS,      "head.first_hidden_to_hidden.bias"},
    {WHISPER_DIAR_TENSOR_HEAD_SPEAKERS_WEIGHT,  "head.single_hidden_to_spks.weight"},
    {WHISPER_DIAR_TENSOR_HEAD_SPEAKERS_BIAS,    "head.single_hidden_to_spks.bias"},
    {WHISPER_DIAR_TENSOR_ENC_NORM1_WEIGHT,      "encoder.layers.%d.norm1.weight"},
    {WHISPER_DIAR_TENSOR_ENC_NORM1_BIAS,        "encoder.layers.%d.norm1.bias"},
    {WHISPER_DIAR_TENSOR_ENC_ATTN_QKV_WEIGHT,   "encoder.layers.%d.attn.w_qkv.weight"},
    {WHISPER_DIAR_TENSOR_ENC_ATTN_OUT_WEIGHT,   "encoder.layers.%d.attn.out_proj.weight"},
    {WHISPER_DIAR_TENSOR_ENC_ATTN_OUT_BIAS,     "encoder.layers.%d.attn.out_proj.bias"},
    {WHISPER_DIAR_TENSOR_ENC_NORM2_WEIGHT,      "encoder.layers.%d.norm2.weight"},
    {WHISPER_DIAR_TENSOR_ENC_NORM2_BIAS,        "encoder.layers.%d.norm2.bias"},
    {WHISPER_DIAR_TENSOR_ENC_FFN1_WEIGHT,       "encoder.layers.%d.ffn.net.0.weight"},
    {WHISPER_DIAR_TENSOR_ENC_FFN1_BIAS,         "encoder.layers.%d.ffn.net.0.bias"},
    {WHISPER_DIAR_TENSOR_ENC_FFN2_WEIGHT,       "encoder.layers.%d.ffn.net.3.weight"},
    {WHISPER_DIAR_TENSOR_ENC_FFN2_BIAS,         "encoder.layers.%d.ffn.net.3.bias"},
    {WHISPER_DIAR_TENSOR_ACTIVITY_HEAD0_WEIGHT, "head.activity_head.0.weight"},
    {WHISPER_DIAR_TENSOR_ACTIVITY_HEAD0_BIAS,   "head.activity_head.0.bias"},
    {WHISPER_DIAR_TENSOR_ACTIVITY_HEAD1_WEIGHT, "head.activity_head.1.weight"},
    {WHISPER_DIAR_TENSOR_ACTIVITY_HEAD1_BIAS,   "head.activity_head.1.bias"},
};

static const std::map<whisper_diar_hparam, const char *> WHISPER_DIAR_HPARAM_NAMES = {
    {WHISPER_DIAR_HPARAM_ARCHITECTURE,                        "general.architecture"},
    {WHISPER_DIAR_HPARAM_VERSION,                             "sortformer.version"},
    {WHISPER_DIAR_HPARAM_ENCODER_TYPE,                        "sortformer.encoder.type"},
    {WHISPER_DIAR_HPARAM_SUBSAMPLING_TYPE,                    "sortformer.encoder.subsampling_type"},
    {WHISPER_DIAR_HPARAM_ENCODER_D_MODEL,                     "sortformer.encoder.d_model"},
    {WHISPER_DIAR_HPARAM_ENCODER_N_HEADS,                     "sortformer.encoder.n_heads"},
    {WHISPER_DIAR_HPARAM_ENCODER_D_FF,                        "sortformer.encoder.d_ff"},
    {WHISPER_DIAR_HPARAM_ENCODER_SUBSAMPLING_FACTOR,          "sortformer.encoder.subsampling_factor"},
    {WHISPER_DIAR_HPARAM_TRANSFORMER_HIDDEN_SIZE,             "sortformer.transformer.hidden_size"},
    {WHISPER_DIAR_HPARAM_ENCODER_N_LAYERS,                    "sortformer.encoder.n_layers"},
    {WHISPER_DIAR_HPARAM_NUM_SPEAKERS,                        "sortformer.num_speakers"},
    {WHISPER_DIAR_HPARAM_ENCODER_POS_EMB_MAX_LEN,             "sortformer.encoder.pos_emb_max_len"},
    {WHISPER_DIAR_HPARAM_PREPROCESSOR_N_FFT,                  "sortformer.preprocessor.n_fft"},
    {WHISPER_DIAR_HPARAM_PREPROCESSOR_FEATURES,               "sortformer.preprocessor.features"},
    {WHISPER_DIAR_HPARAM_PREPROCESSOR_PREEMPH,                "sortformer.preprocessor.preemph"},
    {WHISPER_DIAR_HPARAM_PREPROCESSOR_LOG_ZERO_GUARD,         "sortformer.preprocessor.log_zero_guard"},
    {WHISPER_DIAR_HPARAM_ENCODER_ROPE_BASE,                   "sortformer.encoder.rope_base"},
    {WHISPER_DIAR_HPARAM_SCORING_SPKCACHE_SIL_FRAMES_PER_SPK, "sortformer.scoring.spkcache_sil_frames_per_spk"},
    {WHISPER_DIAR_HPARAM_SCORING_PRED_SCORE_THRESHOLD,        "sortformer.scoring.pred_score_threshold"},
    {WHISPER_DIAR_HPARAM_SCORING_SCORES_BOOST_LATEST,         "sortformer.scoring.scores_boost_latest"},
    {WHISPER_DIAR_HPARAM_SCORING_STRONG_BOOST_RATE,           "sortformer.scoring.strong_boost_rate"},
    {WHISPER_DIAR_HPARAM_SCORING_WEAK_BOOST_RATE,             "sortformer.scoring.weak_boost_rate"},
    {WHISPER_DIAR_HPARAM_SCORING_MIN_POS_SCORES_RATE,         "sortformer.scoring.min_pos_scores_rate"},
};


