name: CI

on:
  workflow_dispatch: # allows manual triggering
  push:
    branches:
      - master
    tags:
      - 'v*'
    paths: ['.github/workflows/build.yml',
            '**/CMakeLists.txt',
            '**/Makefile',
            '**/*.mk',
            '**/*.cmake',
            '**/*.in',
            '**/*.h',
            '**/*.hpp',
            '**/*.c',
            '**/*.cpp',
            '**/*.cu',
            '**/*.cuh',
            '**/*.cl',
            '**/*.swift',
            '**/*.m',
            '**/*.mm',
            '**/*.metal',
            '**/*.comp',
            '**/*.java']

  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - 'bindings/ruby/**'                      # handled by bindings-ruby.yml
      - 'bindings/go/**'                        # handled by bindings-go.yml
      - 'examples/addon.node/**'                # handled by examples.yml
      - '.github/workflows/build-sanitize.yml'  # handled by build-sanitize.yml
      - '.github/workflows/build-linux.yml'     # handled by build-linux.yml
      - '.github/workflows/build-macos.yml'     # handled by build-macos.yml
      - '.github/workflows/build-gcc.yml'       # handled by build-gcc.yml
      - '.github/workflows/build-clang.yml'     # handled by build-clang.yml
      - '.github/workflows/build-sycl.yml'      # handled by build-sycl.yml
      - '.github/workflows/build-windows.yml'   # handled by build-windows.yml
      - '.github/workflows/build-wasm.yml'      # handled by build-wasm.yml
      - '.github/workflows/build-android.yml'   # handled by build-android.yml
      - '.github/workflows/quantize.yml'        # handled by quantize.yml
      - '.github/workflows/coreml.yml'          # handled by coreml.yml
      - '.github/workflows/vad.yml'             # handled by vad.yml
      - '.github/workflows/build-cpu.yml'       # handled by build-cpu.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  ubuntu_image: "ubuntu:22.04"

jobs:
#  freeBSD-latest:
#    runs-on: macos-13
#
#    steps:
#      - name: Clone
#        uses: actions/checkout@v6
#
#      - name: Build
#        uses: cross-platform-actions/action@v0.27.0
#        with:
#          operating_system: freebsd
#          version: '14.2'
#          run: |
#            sudo pkg update
#            sudo pkg install -y gmake sdl2 cmake git
#            cmake -B build
#            cmake --build build --config Release



